# Generated by Django 5.2.8 on 2026-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room_Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
